# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  create:
jobs:
  build:
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    runs-on: ubuntu-latest
    steps:
      - name: 'Call API'
        uses: indiesdev/curl@v1
        id: api
        with:
          url: https://j7g0n43xu7.execute-api.eu-west-1.amazonaws.com/test/blue/version
          method: 'POST'
          accept: 200
          body: '{ "component": "",  "githash": "", "version": "" }'
      - name: 'Use response'
        run: echo ${{ steps.api.outputs.response }}

