# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  create:
jobs:
  build:
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    runs-on: ubuntu-latest
    steps:
      - name: Extract tag name
        id: tag
        uses: actions/github-script@0.2.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            return context.payload.ref.replace(/\/refs\/tags\//, '');
      - name: Extract context
        id: context
        uses: actions/github-script@0.2.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            return context;
      - name: 'show context'
        run: echo ${{  steps.context.outputs.result }}
      - name: 'Call API'
        uses: indiesdev/curl@v1
        id: api
        with:
          url: https://j7g0n43xu7.execute-api.eu-west-1.amazonaws.com/test/blue/version
          method: 'POST'
          accept: 200
          body: "{ \"component\": \"\",  \"githash\": \"\", \"version\": \"${{ steps.tag.outputs.result }}\" }"
      - name: 'Use response'
        run: echo ${{ steps.api.outputs.response }}

